# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - wap98uh

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: acaregistry.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_9FC1F09EF0564569B1AD0784A6671F5F }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_888232642357479C9973C1835CCDBAC4 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: acaregistry.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_9FC1F09EF0564569B1AD0784A6671F5F }}/nginx:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    
    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_DBF9BBEDBC3B44239865212D06CDA729 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_92D0F124C8EB4E42BBEBB29466B801A6 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E09D8DF7239B47DC87ABA62FBE1C1B1A }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'wap98uh'
          slot-name: 'Production'
          images: 'acaregistry.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_9FC1F09EF0564569B1AD0784A6671F5F }}/nginx:${{ github.sha }}'
          